name: ci

on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_REPOSITORY }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
    - name: Docker Pull and run from hub
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: GITHUB_SHA
        script: |
          docker login
          docker pull ${{ secrets.DOCKER_USERNAME }}/posts_node:main
          docker stop posts_node
          docker rm posts_node
          docker run -v /home/ubuntu/proyectos/posts_node:/home/node/app --name posts_node -p 80:3000 node:14
